### PR TITLE
Use hpack to generate cabal file

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
LGTM.

On a slightly related note, is `hpack` available on Hackage? That would be useful to have for generating `base-orphans.cabal` in the future

**Comment by sol** [comment]
It's not on Hackage yet.

I'm still hoping to find a better name.  Initially we called it `cabalize`, which had the problem that it clashes with `cabal` for tab completion on the command-line.  `hpack` doesn't have this problem, but I'm still not sure if it's a good name (feedback and suggestions welcome).

The other thing is that there are still features missing.  To make it work for base-orphans I had to add support for `homepage` and `extra-source-files` first. But with a release early, release often approach that would not be a problem.

Moving forward, I think it makes sense to push it to Hackage with the current name.  I can do that later today.  In case we come up with a better name we can deprecate the old package.

**Comment by RyanGlScott** [comment]
The only downside I can think of for `hpack` is that it's already used for [another software package](https://github.com/twitter/hpack). But it's not on Hackage yet, so you have the liberty of naming it whatever you want.

**Comment by sol** [comment]
`hpack` is on Hackage now.

**Pull request merged**
