### PR TITLE
Add Monoid a => Monad ((,) a)

### PR DESCRIPTION
**Pull request by fumieval**
base-4.8.1.0 has this instance: https://ghc.haskell.org/trac/ghc/ticket/10190

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Would it be okay if we waited until a release candidate of the next version of `base` comes out before adding this instance? I'm a bit hesitant to add it now, since there is a possibility the code in the `Monad ((,) a)` instance could change before it's official.

**Comment by fumieval** [comment]
Ah okay, let us wait.

**Comment by RyanGlScott** [comment]
For bookkeeping purposes, I've started [an issue](https://github.com/haskell-compat/base-orphans/issues/32) which lists all of the forthcoming new instances. I'll link to this pull request so that I remember to merge it when GHC 8.0-rc1 is released.

**Comment by RyanGlScott** [comment]
Thank you!

I'll get to working on the other `base-4.9` instances soon.

**Pull request merged**
